const defaultFilters = [
	"*://*.ebay.com/*",
	"*://pune.craigslist.org//*",
	"*://*.gumtree.com/*",
	"*://*.gumtree.com/*",
	"*://oodle.com/*",
	"*://*.adpost.com/*",
	"*://*.hoobly.com/*",
	"*://*.salespider.com/*",
	"*://*.adsglobe.com/*",
	"*://*.yakaz.com/*",
	"*://*.pornhub.com/*",
	"*://*.8tube.xxx/*",
	"*://*.redtube.com/*",
	"*://*.kink.com/*",
	"*://*.youjizz.com/*",
	"*://*.4chan.com/*",
	"*://*.flickr.com/*",
	"*://*.twitter.com/*",
	"*://*.snapchat.com/*",
	"*://*.toomics.com/*",
	"*://*.tinder.com/*",
	"*://*.Omegle.com/*",
	"*://*.Tumblr.com/*",
	"*://*.whisper.com/*",
	"*://*.kik.com/*",
	"*://*.toomic.com/*",
	"*://*.match.com/*",
	"*://*.meetme.com/*",
	"*://*.facebook.com/*",
	"*://*.pornbaker.com/*",
 	 "*://*.iceporn.com/*",
	"*://*.hardcoreSex.com/*",
	"*://*.beeg.com/*",
	"*://*.xvideos.com/*",
	"*://*.pussyboy.com/*",
	"*://*.xxx.com/*",
	"*://*.xxxpornhd.com/*",
	"*://*.porn.com/*",
	"*://*.porntube.com/*",
	"*://*.3movs.com/*",
	"*://*.propertysex.com/*",
	"*://*.mofos.com/*",
	"*://*.yespornplease.com/*",
	"*://*.18teenporn.com/*",
	"*://*.bunette.com/*",
	"*://*.hornyjav.com/*",
	"*://*.adultmovies.com/*",
	"*://*.fakehub.com/*",
	"*://*.evilangel.com/*",
	"*://*.nubiles.com/*",
	"*://*.RealityKings.com/*",
	"*://*.hclip.com/*",
	"*://*.xxxhdvideos.com/*",
	"*://*.pornvxxx.com/*",
	"*://*.justindianporn.com/*",
	"*://*.xxxpornclips.com/*",
	"*://*.hqtube.com/*",
	"*://*.xxxmovies.com/*",
	"*://*.xxx18video.com/*",
	"*://*.xxxlucah.com/*",
	"*://*.pornhub.com/*",
	"*://*.pornvideos.com/*",
	"*://*.sex.com/*",
	"*://*.hdsexmovies.com/*",
	"*://*.redtube.com/*",
	"*://*.redtubepornhd.com/*",
	"*://*.indiangfvideos.com/*",
	"*://*.fuckmyindiangf.com/*",
	"*://*.indianporn.com/*",
	"*://*.nudeindiangf.com/*",
	"*://*.indianxxxvideos.com/*",
	"*://*.brazzers.com/*",
	"*://*.naughtyamerica.com/*",
	"*://*.defloration.com/*",
	"*://*.xhamster.com/*",
	"*://*.freehdvideos.com/*",
	"*://*.xnxx.com/*",
	"*://*.xhamster.com/*",
	"*://*.rat.com/*",
	
	//add  custom sites here
]

chrome.webRequest.onBeforeRequest.addListener(         //calling google api that contain web request
	                                                //that too before sending data
    function(details) { return { cancel: true }},  //3 argument 1)function callback that contains detailsthat we are sending
                                                      //cancel true will block all the reqest
    { urls: defaultFilters },         // filter that contails which sites we want to block
    ["blocking"]                      // pass blocking option array
)
